version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - "Quantalabs"
    commit-message:
      prefix: "[dep]"
      prefix-development: "[dep/dev]"
    labels:
      - "dependabot"
    
