version = 1

test_patterns = [
    "tests/**",
    "**/test_*"
]

exclude_patterns = [
    "dist/*",
    "build/*",
    "docs/*",
]

[[analyzers]]
name = "python"
enabled = true
dependency_file_paths = [
    "requirements/requirements.txt",
    "requirements/requirements-nightly.txt",
    "requirements/requirements-dev.txt"
]

  [analyzers.meta]
  runtime_version = "3.x.x"
