
name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Thanks for contributing! Make sure you follow the issue template given for your type, or use a blank one if you are submitting an issue unrelated to the templates.'
        pr-message: "Thank you for contributing! Make sure to follow the PR Template and we'll make sure to merge it ASAP!"
